version: 2
jobs:
  versioning:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y jq
            sudo apt install -y moreutils
            sudo snap install yq
      - run: 
          name: Version check
          command: |
            # Check if commit SHA matches
            LATEST_VERSION_COMMIT="$(curl https://api.github.com/repos/RPCS3/rpcs3/commits/master -s | jq .sha -r)"
            CURRENT_VERSION_COMMIT="$(yq e '.parts.rpcs3.source-commit' snap/snapcraft.yaml)"

            # compare versions
            if [ $CURRENT_VERSION_COMMIT != $LATEST_VERSION_COMMIT ]; then
                echo "commits don't match, github: $LATEST_VERSION_COMMIT snap: $CURRENT_VERSION_COMMIT"
                echo "updating rpcs3 source commit"
                yq eval ".parts.rpcs3.source-commit = \"$LATEST_VERSION_COMMIT\"" -i snap/snapcraft.yaml
                echo 'export BUILD="true"' >> $BASH_ENV
                echo "export LATEST_VERSION_COMMIT=$LATEST_VERSION_COMMIT" >> $BASH_ENV
            else
                echo "commits match, github: $LATEST_VERSION_COMMIT snap: $CURRENT_VERSION_COMMIT"
                echo 'export BUILD="false"' >> $BASH_ENV
                echo 'export BUILD="false"' >> build
            fi
      - persist_to_workspace:
            root: ./
            paths:
                - "./"
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Copy build variable from temp file
          command: |
            if [ -f build ]; then
              cat build >> $BASH_ENV
            fi
      - run:
          name: Versions match - Cancel
          command: |
            if [ ${BUILD} == false ]; then
              circleci-agent step halt
            fi
      - run:
          name: Snap build
          command: |
            sudo snapcraft --use-lxd
      - run:
          name: Snap Test
          command: |
            sudo snap install *.snap --dangerous
            snap run rpcs3-emu.rpcs3 --version
      - persist_to_workspace:
            root: ./
            paths:
                - "./"
      # - run:
      #     name:
      # - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
      #     path: "*.snap"
  publish:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Copy build variable from temp file
          command: |
            if [ -f build ]; then
              cat build >> $BASH_ENV
            fi
      - run:
          name:  Build cancelled - Cancel Publish
          command: |
            if [ ${BUILD} == false ]; then
              circleci-agent step halt
            fi
      - run:
          name: Install Publish dependencies
          command: |
            sudo apt update
            sudo apt install -y jq
            sudo apt install -y moreutils
      - run:
          name: "Publish to Snap Store"
          command: |
            mkdir .snapcraft
            echo $SNAP_STORE_LOGIN | base64 --decode --ignore-garbage > .snapcraft/store-login.txt
            snapcraft login --with .snapcraft/store-login.txt
            snapcraft upload *.snap --release edge
            rm -rf .snapcraft
      - run:
          name: Updating versions.json
          command:  |
            export BUILT_SNAP_VERSION="$(ls *.snap | cut -f2 -d '_')"
            echo $BUILT_SNAP_VERSION
            cat versions.json | jq ".edge = \"$BUILT_SNAP_VERSION\"" | sponge versions.json
            git config --global user.name 'Nightmayr'
            git config --global user.email 'umayr23@gmail.com'
            git commit -am "Updating version [ci skip]"
            git push -q https://${GITHUB_PAT}@github.com/Nightmayr-snaps/rpcs3-snap.git master

workflows:
  version: 2

  build-and-publish:
    jobs:
      - versioning:
          filters:
            branches:
              only: master
      - build:
          requires:
            - versioning
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master

  build-and-publish-cron:
    triggers:
      - schedule:
          cron: "0 0,5,10,15,20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - versioning
      - build:
          requires:
            - versioning
      - publish:
          requires:
            - build
  
  build:
    jobs:
      - versioning
      - build:
          requires:
            - "versioning"
          filters:
            branches:
              ignore: master
  
  
